" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

let color = "true"
syntax on

set mouse=a
set ttymouse=""

"set fdm=syntax
"set foldlevelstart=20

set shiftwidth=4
set tabstop=4
set expandtab
colorscheme desert

set ruler

set cindent
set autoindent
set smartindent

set fileencodings=utf-8,big5,euc-jp,gbk,euc-kr,utf-bom,iso8859-1
set encoding=utf8
set tenc=utf8
